business:
  info: Business Microservice Development
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/prod
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB